# Generated by Django 2.0.4 on 2018-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0002_object_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
